### ISSUE TITLE
Alphabetize names in ballot

### ISSUE THREAD

**Issue by sumeetjain** [omahacodeschool/tag-awards#246]
For the dropdowns on ballot pages, the list of names should be alphabetized. (Last name, first name, anything really--it doesn't matter. Emily just knows that if there isn't some kind of apparent ordering, people will complain that TAG deliberately put certain artists at the top of the list.)

**Comment by jlocatis** [comment]
Done for nominations ballot.

**Comment by jlocatis** [comment]
Done for final ballot.
