### ISSUE TITLE
Questions for Emily and Ronnie of TAG

### ISSUE THREAD

**Issue by amymariewall** [omahacodeschool/tag-awards#54]
- [ ] Would it be possible for us to get a copy of a past ballot?
- [ ] Would you be willing to use random voter ID keys that are automatically generated by a system we install? If not, what system do you prefer?
- [ ] When would you prefer to go in and correct errors on nomination forms? Would it be more convenient to do that as they are submitted or all at once?
- [ ] Do members frequently nominate multiple people at once or just one?

**Comment by mel-d** [comment]
What's your points system for assigning weights to votes?

**Comment by sumeetjain** [comment]
Sample ballot: http://cl.ly/fUiK/TAGAwardsNominationBallot2015.docx.pdf

**Comment by santaclauslives** [comment]
- [ ] Use of TAG logo. TAG has at least 2 I have seen. Is there one we can use with our app, and are there any style-guide considerations with using it?
- [ ] Related question about whether TAG has a style guide/color palette?
- [ ] The sample nomination ballot has a category for "Outstanding Achievement in Directing - Musical" and another one for "Oustanding Achievement by a Musical Director." I want to make sure about whether those are two separate awards.

**Comment by sumeetjain** [comment]
We can create the codes ourselves! They'll just need a page that shows them members names <> codes, for their reference.

**Comment by sumeetjain** [comment]
> "Use of TAG logo. TAG has at least 2 I have seen. Is there one we can use with our app, and are there any style-guide considerations with using it?"

http://cl.ly/fW1i/restudentquestions.zip

> "Related question about whether TAG has a style guide/color palette?"

Using Black and White with Red accent. 

> "The sample nomination ballot has a category for "Outstanding Achievement in Directing - Musical" and another one for "Oustanding Achievement by a Musical Director." I want to make sure about whether those are two separate awards."

Those are two separate awards.

**Comment by amymariewall** [comment]
> We can create the codes ourselves! They'll just need a page that shows them members names <> codes, for their reference.

Just to clarify, do you mean we can determine the unique voter tokens that get assigned to each user?

**Comment by mel-d** [comment]
Do users tend to make just a few nominations, or do most who fill out the nomination form fill it out to near completion?
